### ISSUE TITLE
[vue] jqx widget component makes dummy html elements

### ISSUE THREAD

**Issue by EnochG1** [jqwidgets/jQWidgets#123]
Hi, when I used vue-router, I saw new html elements are appended to the end of <body> like below. The red square div is actual necessary elements but each jqx component makes dummy div elements. 
![image](https://user-images.githubusercontent.com/19601207/57125816-bf7aed00-6dc5-11e9-8452-1efd287f7ef1.png)

I think it is unusable and make page loading so slow. And I think I can't handle it because your demo page also have this dummy element.

https://www.jqwidgets.com/vue/vue-datetimeinput/#https://www.jqwidgets.com/vue/vue-datetimeinput/vue-datetimeinput-defaultfunctionality.htm
![image](https://user-images.githubusercontent.com/19601207/57125901-14b6fe80-6dc6-11e9-988a-2c68cd458bd5.png)

Cause Vue.js is optimized for SPA, I think it makes jqwidgets awful for Vue. As I change the menu, new dummy element is appended but can't remove until single page refreshed.
Hope you can check and fix this problem ASAP.

thanks

**Comment by jqwidgets** [comment]
Hi EnochG1,

It does not create dummy elements. It creates Popup elements. In order to correctly position a Popup, it should be part of the document's body tag with absolute position, high z-index and with top and left properties left. The behavior is by design and is correct. It does not matter that the application is based on Vue and the elements are with display: none;
